src/K8sHttpClient/KubeHttpClientSettingsProvider.cs, tests/UnitTests/KuteHttpClientSettingsProviderTests.cs
Old format: 4:cpu,cpuacct:/docker/{container_id}
New format: 6:cpu,cpuacct:{pod_name}/{container_id}
=> Support new format of cgroup path.

src/Extensions/ApplicationInsightsExtensions.cs
Readiness Probe will disable the communication between the pod and the master until the app is ready; Before the fix, the app will not ready until AI.K8s is initialized; AI.K8s will not be ready until it can talk with master and there we go a dead loop. :-(
The fix simply dispatches the initialization into a different thread so that the main app will still become ready and serves request even when AI.K8s is not yet ready. This might lead to a few initial request telemetry being sent without K8s info, it is still better than the dead loop.
This fix address #73.
Tested with the following configure.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: k8s-debugger
spec:
replicas: 2
template:
metadata:
labels:
app: webapp
spec:
containers:
- name: k8s-web
image: …
```
=> Fix the deadlock when Readiness Probe is configured

src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs
This commit will update the documentation of
ApplicationInsightsExtensions.Enablekubernetes with information that
this method can be used to inject the Kubernetes telemetry initializer
if you are running in a non ASP.NET environment, like a console app
for example.
=> Update documentation EnableKubernetes

examples/BasicUsage/BasicUsage.csproj, examples/BasicUsage/README.md, examples/BasicUsage_clr21_RBAC/README.MD, examples/BasicUsage_clr21_RBAC/app/app.csproj, examples/MultipleIKeys/MultipleIKeys.csproj, examples/MultipleIKeys/Startup.cs, examples/WindowsContainer/AspNetCoreNano.csproj, examples/WindowsContainer/README.md, examples/ZeroUserCodeLightup/Dockerfile, examples/ZeroUserCodeLightup/README.md, examples/ZeroUserCodeLightup/ZeroUserCodeLightup.csproj
Addresses #142 
1. Address vulnerability issues by bumping up external package versions in the examples.
2. Bump up the references to the NuGet package of AI.K8S itself to the latest non-prerelease version.
=> Update package versions

src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs
configure k8s enricher for a given TelemetryConfiguration as default
instead of adding it in the dependency injection system.
important: the configuration will be invoked at a different point in time during
the host building proccess (pipeline).
it prevents circular dependencies issues while using Microsoft Extensions Logging
for Application Insights and should be backwards compat.
solved: #173
=> solve AppInsights-K8s compat issue with MEL

src/ApplicationInsights.Kubernetes.HostingStartup/K8sInjection.cs
now K8sInjection will use the the app's configuration providers in addition
to those added automatically by CreateDefaultBuilder
- remove UseApplicationInsights in favor of adding
- enable users to configure its app using other providers like
AzureKeyVaultConfigurationProvider
Important: configuration providers are available at IHostingStartup
configure time provided they are added as App Configuration.
For more information, please take a look at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#configureappconfiguration
Solved: #175
=> use the app's config providers for Zero Light Up

src/ApplicationInsights.Kubernetes/Debuggings/ApplicationInsightsKubernetesDiagnosticSource.cs
Simply prefix message with a timestamp for diagnostic logs. Address #189 .
=> Add timestamp to diagnostic source logs

src/ApplicationInsights.Kubernetes/K8sQueryClient.cs
Right now, if you fail to fetch K8sEntityList, _null_ is returned. This leads to exception on application startup.
`System.ArgumentNullException: Value cannot be null.
Parameter name: source
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory.CreateAsync(DateTime timeoutAt)`
Btw. this message says absolutely nothing.
=> do no return null from K8sQueryClient

src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs, src/ApplicationInsights.Kubernetes/TelemetryInitializers/TelemetryProperty.cs
As we discussed in #206 , avoid string interpolation every telemetry initialization.
=> Pre-form property names for telemetries in initializer

src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
This will address #228 by limited test in Azure Function environment.
Considering:
* .NET Core 3.1 LTS still have a long lifetime, 
* We aren't use any 5.x specific APIs.
It isn't bad to lower the entrance for Azure Functions.
=> Downgrade dependencies

src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
Because of https://github.com/JamesNK/Newtonsoft.Json/issues/2535 and https://alephsecurity.com/vulns/aleph-2018004
=> Update Newtonsoft.Json naar 13.0.1 to mitigate DOS vulnerability

src/ApplicationInsights.Kubernetes/Debuggings/KubernetesDebuggingServiceCollectionBuilder.cs, src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs, src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs, src/ApplicationInsights.Kubernetes/TelemetryInitializers/SimplePerformanceCounterTelemetryInitializer.cs, tests/UnitTests/KubernetesTestServiceCollectionBuilder.cs
Address #236.
The issue is caused by the fact a pre-matured service provider is built during the service registration. Bad practice:
Code:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/ad6974f1c994c3f48e6ce11e779b878a7203c92a/src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs#L127
=> Avoid building pre-mature service provider

src/ApplicationInsights.Kubernetes/ContainerIdProviders/CGroupContainerIdProvider.cs
This is required by the implementation that uses `string.Format`. See bug #257.
Source code has been scanned, no other spot found with similar issue.
=> Avoid using string place holder

examples/ZeroUserCodeLightup.Net6/README.md, examples/ZeroUserCodeLightup.Net6/k8s.yaml, examples/k8s-namespace.yaml
* Show an example of deploying resources to a dedicated namespace than the default.
* Add more details for RBAC & testing steps of port-forwarding.
* Small rephrases.
=> Update readme for Hosting Startup Example for .NET 6

src/ApplicationInsights.Kubernetes/K8sHttpClient/KubeHttpClientSettingsBase.cs, tests/UnitTests/KuteHttpClientSettingsProviderTests.cs
Address #297 
- Remove the unexpected exception when auto-detect of container id failed.
- Add a unit test to cover for regression.
- Piggyback to fix a unit test method name typo.
=> Remove unexpected exception when container id can not be detected

dev/F5WebApi/appsettings.json, src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj, src/ApplicationInsights.Kubernetes/Containers/ContainerStatusManager.cs, src/ApplicationInsights.Kubernetes/Containers/IContainerStatusManager.cs, src/ApplicationInsights.Kubernetes/Extensions/AppInsightsForKubernetesOptions.cs, src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs, src/ApplicationInsights.Kubernetes/IK8sEnvironmentHolder.cs, src/ApplicationInsights.Kubernetes/Interfaces/IK8sEnvironmentFactory.cs, src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs, src/ApplicationInsights.Kubernetes/K8sEnvironmentHolder.cs, src/ApplicationInsights.Kubernetes/K8sInfoBackgroundService.cs, src/ApplicationInsights.Kubernetes/Pods/IPodInfoManager.cs, src/ApplicationInsights.Kubernetes/Pods/PodInfoManager.cs, src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs, tests/UnitTests/K8sEnvironemntFactoryTests.cs, tests/UnitTests/KubernetesEnablementTests.cs, tests/UnitTests/KubernetesTelemetryInitializerTests.cs
Addresses #301, #302 
Leverage background service for getting cluster-info.
* Simplified the telemetry initializer
* Enables refresh cluster-info by configured intervals.
Reimplement timeout by using a cancellation token than a stub task.
Piggyback some small refactors.
=> Using background service to fetch k8s cluster info

src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
Drop explicit dependency to Newtonsoft.Json.
By investigation, Newtonsoft.Json is still on the dependency chain. The intention is:
1. No explicit dependency on it;
2. When we are ready to upgrade to use a higher version of `Kubernetes.Client`, it won't be a blocking issue;
The bottom line, is there is nothing functionally wrong with using `Newtonsoft.Json`.
=> Drop Newtonsoft.Json

tests/UnitTests/UnitTests.csproj
Addresses #329 
Brings up the dependency of Newtonsoft.Json to 13.0.1 from 9.0.1 for compliance.
New dependency graph:
=> Bump up unit test sdk to 17.4.0

dev/F5WebApi/F5WebApi.csproj, src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj, src/ApplicationInsights.Kubernetes/K8sClientService.cs, src/Directory.Build.props
Address #332 
* Bump up the major version to drop support for `.NET Core 3.1` for the newer packages.
* `.NET Core 3.1` is out of support on 12/13/2023. For more info: <https://dot.net>
The existing 3.x package will be kept for a while so that there's time to mitigate existing projects to `6.x`. We will check the download data to determine when to fully remove `Microsoft.ApplicationInsights.Kubernets 3.x`.
=> Application Insights for Kubernetes 6.0

src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs, src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs, src/ApplicationInsights.Kubernetes/IK8sInfoBootstrap.cs, tests/UnitTests/AppInsightsKubernetesOptionsTests.cs, tests/UnitTests/ApplicationInsightsExtensionsTests.cs, tests/UnitTests/KubernetesEnablementTests.cs
There is a limitation that there can't be any HostedService registered in the dependency injection container in in-proc Azure Function.
This is an update to:
1. Allow the user to choose to skip registering the BackendService.
2. Expose `IK8sInfoBootstrap` as an alternative to allow the user to invoke it manually.
I would need to provide documentation in the future for the usage.
Tagging @mavsankar since he's asking for the feature.
=> Support In-Proc Azure Function in K8s

src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
Proposal #344 
Fallback method if container id has not provided.
Read ContainerName environment variable and find first container by name
=> Added fallback method select container by name

src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
Fixes https://github.com/microsoft/ApplicationInsights-Kubernetes/issues/357.
=> Upgrade KubernetesClient dependency

src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj, src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs, src/ApplicationInsights.Kubernetes/K8sInfoBootstrap.cs
Addresses #355.
This is a smaller change, with better backward compatibility than #356.
Thanks for @tomaszzmuda for reporting the issue and provided a potential fix.
=> Support keyed service collection

src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs, src/ApplicationInsights.Kubernetes/Containers/ContainerStatusManager.cs
=> Updating logging a bit

src/ApplicationInsights.Kubernetes/Debuggings/ApplicationInsightsKubernetesDiagnosticSource.cs, tests/UnitTests/ApplicationInsightsKubernetesDiagnosticSourceTests.cs
Fixes a bug when string format crashes on messages that shouldn't be formatted.
=> fixes logger #378

src/ApplicationInsights.Kubernetes/Extensions/AppInsightsForKubernetesOptions.cs, src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs, tests/UnitTests/K8sEnvironemntFactoryTests.cs
Some companies do not allow all pods to call the nodes api in the cluster, 
Currently there is no way to skip the call to the nodes endpoint, which if you do not have the permission will potentially make noise in the logs showing a lot of failed (403 Forbidden) HTTP requests (see below). 
`K8sClientService.GetNodesAsync` ignores the forbidden response, by returning an empty `IEnumerable<V1Node>`, but the request is still being performed.
This change adds an option to `ExcludeNodeInformation`, which you can set to `true`, if you want to skip the call to nodes endpoint entirely - typically because you don't have permission (and likely won't get it) to call the endpoint.
=> Ability to exclude node information
