microsoft/ApplicationInsights-Kubernetes

- src/ApplicationInsights.Kubernetes.csproj
- tests/UnitTests/UnitTests.csproj
> Multi-target .NET Standard 1.3 & .NET Standard 2.0

- src/ApplicationInsights.Kubernetes.csproj
> Appending support for netstandard 1.6

- src/ApplicationInsights.Kubernetes.csproj
- src/Extensions/ApplicationInsightsExtensions.cs
- src/IK8sQueryClient.cs
- src/K8sEnvironment.cs
- src/K8sEnvironmentFactory.cs
- src/K8sHttpClient/KubeHttpClientFactory.cs
- src/K8sHttpClient/KubeHttpClientSettingsProvider.cs
- src/K8sQueryClient.cs
- src/K8sQueryClientFactory.cs
- src/TelemetryInitializers/KubernetesModule.cs
- src/TelemetryInitializers/KubernetesTelemetryInitializer.cs
- tests/UnitTests/KubernetesModuleTests.cs
- tests/UnitTests/KubernetesTelemtryInitializerTests.cs
A simple refactor to align with .NET Standard dependency injection coding model. #86.
> Service collection implementation

- src/ApplicationInsights.Kubernetes.HostingStartup/ApplicationInsights.Kubernetes.HostingStartup.csproj
- src/ApplicationInsights.Kubernetes.HostingStartup/K8sInjection.cs
> Enable Applicaiton Insights for hoststartup scenario

- examples/BasicConsoleApp/src/saRole.yaml
- examples/BasicUsage_clr21_RBAC/README.MD
- examples/BasicUsage_clr21_RBAC/k8s/saRole.yaml
- examples/BasicUsage_clr21_RBAC/k8s/saRoleMoreNS.yaml
- examples/WindowsContainer/k8s/saRole.yaml
Update the example due to #219
> Dev/saars/update doc rbac - multiple namespaces

- src/ApplicationInsights.Kubernetes/Extensions/AppInsightsForKubernetesOptions.cs
- src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/ITelemetryKeyCache.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/SimplePerformanceCounterTelemetryInitializer.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/TelemetryKeyCache.cs
- tests/UnitTests/KubernetesTelemetryInitializerTests.cs
- tests/UnitTests/TelemetryKeyCacheTests.cs
> Add telemetry key cache to allow altering telemetry key scenario

- NuGet.config
> Clean up nuget feeds

- examples/BuildOutOfContainer/.vscode/tasks.json
- examples/BuildOutOfContainer/BuildOutOfContainer.csproj
- examples/BuildOutOfContainer/Controllers/WeatherForecastController.cs
- examples/BuildOutOfContainer/Dockerfile
- examples/BuildOutOfContainer/K8s.yaml
- examples/BuildOutOfContainer/Program.cs
- examples/BuildOutOfContainer/Readme.md
- examples/BuildOutOfContainer/Startup.cs
- examples/BuildOutOfContainer/WeatherForecast.cs
- examples/BuildOutOfContainer/appsettings.json
* .NET 5
* Using Application Insights SDK with connection string
* Docker: Simplified dockerfile to build the binary locally
* K8s: Example of using NodePort for service to debug locally
> Add an example

- README.md
Makes the package easier to find + shows latest version number automatically
live preview: https://github.com/304NotModified/ApplicationInsights-Kubernetes/tree/patch-1
> Added NuGet badge to Readme

- examples/BasicUsage/README.md
- examples/WindowsContainer/README.md
Append the info that `PublishWithAspNetCoreTargetManifest` is not needed as asked in #251
> Update windows container example

- tests/UnitTests/KubernetesEnablementTests.cs
- tests/UnitTests/UnitTests.csproj
Failed the unit test by accident in #264. Issue was found and tracked by #266.
I'll spin up another PR for `PR build` by GitHub action.
> Update unit tests accordingly

- dev/F5WebApi/Program.cs
- dev/F5WebApi/Readme.md
- dev/F5WebApi/dockerfile
- dev/F5WebApi/k8s.yml
Add some artifacts to help deploy F5 project, make it easier to deploy to K8s cluster for debugging.
> Add dockerfile and k8s for F5 project

- docs/SelfDiagnostics.MD
With 2.0.4-beta1, turning on self-diagnostic has been simplified. Update the documentation to reveal it.
Addressing #262
> Update readme for self-diagnostics

- examples/WorkerExample/Program.cs
- examples/WorkerExample/Readme.md
- examples/WorkerExample/WorkerExample.csproj
- examples/WorkerExample/k8s.yml
* Recommend deploying to custom namespace
* Link to RBAC configuration
* Some small changes
> Refresh worker example

- src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
- src/ApplicationInsights.Kubernetes/Containers/ContainerIdNormalizer.cs
- src/ApplicationInsights.Kubernetes/Containers/IContainerIdNormalizer.cs
- src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs
- src/ApplicationInsights.Kubernetes/Utilities/StringUtils.cs
- tests/UnitTests/AppInsightsKubernetesOptionsTests.cs
- tests/UnitTests/ApplicationInsightsExtensionsTests.cs
- tests/UnitTests/CGroupContainerIdProviderTests.cs
- tests/UnitTests/ContainerDMountInfoContainerIdMatcherTests.cs
- tests/UnitTests/ContainerIdHolderTests.cs
- tests/UnitTests/ContainerIdNormalizerTests.cs
- tests/UnitTests/DockerEngineMountInfoContainerIdMatcherTests.cs
- tests/UnitTests/EnvironmentVariableContainerIdProviderTest.cs
- tests/UnitTests/EnvironmentVariablePodNameProviderTests.cs
- tests/UnitTests/KubernetesEnablementTests.cs
- tests/UnitTests/KubernetesTelemetryInitializerTests.cs
- tests/UnitTests/LoggingLevelFixture.cs
- tests/UnitTests/PodInfoManagerTests.cs
- tests/UnitTests/StringUtilsTest.cs
- tests/UnitTests/TelemetryKeyCacheTests.cs
- tests/UnitTests/TestDiagnosticSourceObserver.cs
Address #292 for porting changes to 3.x.
> Dev/saars/normalize container (#293)

- docs/configure-rbac-permissions.md
- docs/sa-role-none-cluster.yaml
- src/ApplicationInsights.Kubernetes/IK8sQueryClient.cs
- src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs
- src/ApplicationInsights.Kubernetes/K8sQueryClient.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs
- tests/UnitTests/K8sQueryClientTests.cs
- tests/UnitTests/KubernetesTelemetryInitializerTests.cs
> Support telemetry enhancement without cluster role

- dev/F5WebApi/Program.cs
- src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs
- src/ApplicationInsights.Kubernetes/Extensions/KubernetesServiceCollectionBuilder.cs
- src/ApplicationInsights.Kubernetes/Pods/PodInfoManager.cs
> Clean up lifetime of registered services

- src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
- src/ApplicationInsights.Kubernetes/Readme.Nuget.md
There will be a simple readme file displayed on the NuGet package page directly.
> Add a readme to NuGet package

- README.md
- docs/SelfDiagnostics.MD
- docs/configure-rbac-permissions.md
- examples/WebAPI.Net6/MinimalAPI/.dockerignore
- examples/WebAPI.Net6/MinimalAPI/MinimalAPI.csproj
- examples/WebAPI.Net6/MinimalAPI/Program.cs
- examples/WebAPI.Net6/MinimalAPI/Properties/launchSettings.json
- examples/WebAPI.Net6/MinimalAPI/appsettings.json
- examples/WebAPI.Net6/MinimalAPI/dockerfile
- examples/WebAPI.Net6/MinimalAPI/k8s.yaml
- examples/WebAPI.Net6/Readme.md
- examples/WebAPI.Net6/WebAPI/Controllers/WeatherForecastController.cs
- examples/WebAPI.Net6/WebAPI/NormalWebAPI.csproj
- examples/WebAPI.Net6/WebAPI/Program.cs
- examples/WebAPI.Net6/WebAPI/Properties/launchSettings.json
- examples/WebAPI.Net6/WebAPI/WeatherForecast.cs
- examples/WebAPI.Net6/WebAPI/appsettings.Development.json
- examples/WebAPI.Net6/WebAPI/appsettings.json
- examples/WebAPI.Net6/WebAPI/dockerfile
- examples/WebAPI.Net6/WebAPI/k8s.yaml
- examples/WorkerExample/Program.cs
- examples/WorkerExample/Readme.md
- examples/WorkerExample/WorkerExample.csproj
- examples/WorkerExample/k8s.yml
- examples/ZeroUserCodeLightup.Net6/README.md
- examples/ZeroUserCodeLightup.Net6/k8s.yaml
- examples/k8s-namespace.yaml
- src/ApplicationInsights.Kubernetes/Containers/ContainerIdNormalizer.cs
- src/ApplicationInsights.Kubernetes/Containers/IContainerIdNormalizer.cs
This is a merge from `develop` branch to `feature/3.0`, this prepares the RI from `feature/3.0` back to `develop` branch.
> Forward integration from develop to feature/3.0

- src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
- src/ApplicationInsights.Kubernetes/Containers/ContainerStatusManager.cs
- src/ApplicationInsights.Kubernetes/K8sClientService.cs
- src/ApplicationInsights.Kubernetes/K8sEnvironmentFactory.cs
- src/ApplicationInsights.Kubernetes/Pods/PodInfoManager.cs
> Bump up KubernetesClient to 7.2.19 from 6.0.26

- src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
- src/ApplicationInsights.Kubernetes/Extensions/AppInsightsForKubernetesOptions.cs
- src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs
- src/ApplicationInsights.Kubernetes/IClusterEnvironmentCheck.cs
- src/ApplicationInsights.Kubernetes/K8sInfoBackgroundService.cs
- tests/UnitTests/AlwaysInClusterCheck.cs
- tests/UnitTests/ContainerIdHolderTests.cs
- tests/UnitTests/ServiceProviderLifetimeValidationTests.cs
> Fix Bug: Service scope captive for ContainerIdProviders inside ContainerIdHolder

- .github/workflows/ci.yml
- src/ApplicationInsights.Kubernetes.HostingStartup/ApplicationInsights.Kubernetes.HostingStartup.csproj
* Fix issue: Missed bumping up hosting startup to 6.0
* Update CI: covering hosting startup project
* Piggyback: Update CI pipeline to cover debug/release configurations
> Hosting startup 6.0

- src/ApplicationInsights.Kubernetes/IK8sEnvironment.cs
- src/ApplicationInsights.Kubernetes/K8sEnvironment.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/KubernetesTelemetryInitializer.cs
- src/ApplicationInsights.Kubernetes/TelemetryInitializers/TelemetryProperty.cs
- tests/UnitTests/KubernetesTelemetryInitializerTests.cs
> Added support to capture image name in the telemetry

- src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
- src/Directory.Build.props
7.x will work with KubernetesClient >= 12.1.1
> Get ready for 7.x package

- src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
Allows K8sClient versions: [10.0.16, 12.1.0)
> Do not allow break change in K8sClient

- src/ApplicationInsights.Kubernetes.HostingStartup/ApplicationInsights.Kubernetes.HostingStartup.csproj
- src/ApplicationInsights.Kubernetes/ApplicationInsights.Kubernetes.csproj
- tests/UnitTests/UnitTests.csproj
> Replace vulnerable dependencies
